apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    replicate: "true"
  name: allow-all-ingress
  namespace: capsule-system
spec:
  ingress:
    - {}
  podSelector: {}
  policyTypes:
    - Ingress
